from . import student
from . import subject
from . import skill
from . import exam_type
from . import attendance
from . import leave
from . import exam
from . import result
from . import dashboard
