{
    'name': 'Student Administration',
    'version': '1.0',
    'summary': 'Manage student records, attendance, leave, and exam results',
    'category': 'Education',
    'author': 'Your Name',
    'depends': ['base', 'spreadsheet', 'spreadsheet_dashboard', 'Student_Management', 'student_attendance', 'student_leave'],
    'data': [
        'security/ir.model.access.csv',
        'views/actions.xml',
        'views/student_views.xml',
        'views/subject_views.xml',
        'views/skill_views.xml',
        'views/exam_type_views.xml',
        'views/attendance_views.xml',
        'views/leave_views.xml',
        'views/exam_views.xml',
        'views/result_views.xml',
        'views/dashboard_views.xml',
        'views/menu.xml',
        'data/dashboard.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
}
